name: Build and test on push
on: push
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Switch Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.0
      - name: Compile & test
        run: npm i && npm run compile && npm test
      - name: Run node
        run: npm run node
  frontend:
    needs: backend
    runs-on: ubuntu-latest
    steps:
      - name: Deploy contracts
        run: npm run deploy:local
      - name: Test & build
        run: cd frontend && npm i && CI=true npm test && npm run build
